### PR TITLE
Use generic notebook insert cell command instead of jupyter specific

### PR DESCRIPTION
**Pull request by AndreasArvidsson**

### CODE REVIEW

**Comment by pokey** [comment]
How come you closed this one?  Because it breaks the text-based setup?

**Comment by AndreasArvidsson** [comment]
I don't think so

**Comment by pokey** [comment]
Can you not just do something like this and then check if it's null? https://github.com/cursorless-dev/cursorless-vscode/blob/04fcbfeaa362564d13f8bea5932675204055d76f/src/util/setSelectionsAndFocusEditor.ts#L54-L56

**Comment by AndreasArvidsson** [comment]
Not a pretty solution but might work. Okay it's back on the list.

**Comment by AndreasArvidsson** [comment]
@pokey Turned out quite nicely actually

**Review by pokey — COMMENTED** [review]
Yes looks great!  Test please 😊

**Comment by AndreasArvidsson** [comment]
How do you propose we make tests for a notebook?

**Comment by pokey** [comment]
> How do you propose we make tests for a notebook?

like this https://github.com/cursorless-dev/cursorless-vscode/blob/main/src/test/suite/crossCellsSetSelection.test.ts

**Comment by AndreasArvidsson** [comment]
Thanks test is now added.

**Comment by pokey** [comment]
I made the checks a bit more thorough and did some quick refactoring while I was there https://github.com/cursorless-dev/cursorless-vscode/pull/486/files/a37d5474c5cfbd9360f0d077162390c1ca7e3e25..4b02b6039fe6d57ad8ed25eadf906f1e016a6e27

**Comment by AndreasArvidsson** [comment]
Good changes

**Review by pokey — APPROVED** [review]

**Pull request merged**
