### PR TITLE
Add link wrap gif

### PR DESCRIPTION
**Pull request by pokey**

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
Should we really add a gif to a feature that is not in vscode? I do believe this is one of your custom snippets?

**Comment by pokey** [comment]
Yeah I had that thought too, but people keep asking whether Cursorless is useful for things other than code so I thought this one was a nice illustration of Cursorless for markdown. Plus I think it's kinda cool

Shall I just add the snippet to Cursorless core?

**Comment by AndreasArvidsson** [comment]
I definitely think that some work down examples are in order. But examples that the user country produce are probably not good ux. 

Maybe. We should probably have a proper discussion about snippets. I know you have a lot of thoughts and ideas about them but we haven't really had a proper discussion about it.

**Comment by pokey** [comment]
So I think the best argument against including this GIF in the README is that wrapper snippets are still marked as experimental.  Forgot about that detail 😅

Given that they are experimental, I don't think there's much harm in adding "link wrap" snippet to cursorless, though.

What if I removed the GIF from the README, but added it to the experimental docs for wrapper snippets and added `"link wrap"` snippet to core?  I think it's a nice experimental snippet and nicely illustrates the power of Cursorless for editing non-code text

**Comment by AndreasArvidsson** [comment]
I think that sounds fine

**Comment by pokey** [comment]
Done

**Review by AndreasArvidsson — APPROVED** [review]

**Pull request merged**
